// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNoIrPYR4Ng24wcDkNVm2m0VNqbjMNmoI',
    appId: '1:447295207162:web:fd75f0b2129552dd633b43',
    messagingSenderId: '447295207162',
    projectId: 'chatso-2cb01',
    authDomain: 'chatso-2cb01.firebaseapp.com',
    storageBucket: 'chatso-2cb01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0iiUpd3NZKtRMw-X7_sWv1mq3vIOooo',
    appId: '1:447295207162:android:bd3f26e6fdfaf57a633b43',
    messagingSenderId: '447295207162',
    projectId: 'chatso-2cb01',
    storageBucket: 'chatso-2cb01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwAFQWwwEsfD3INwqV1_DEtD6iyuIBpyA',
    appId: '1:447295207162:ios:3d65ba6bbed16802633b43',
    messagingSenderId: '447295207162',
    projectId: 'chatso-2cb01',
    storageBucket: 'chatso-2cb01.firebasestorage.app',
    iosBundleId: 'com.example.chatso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwAFQWwwEsfD3INwqV1_DEtD6iyuIBpyA',
    appId: '1:447295207162:ios:3d65ba6bbed16802633b43',
    messagingSenderId: '447295207162',
    projectId: 'chatso-2cb01',
    storageBucket: 'chatso-2cb01.firebasestorage.app',
    iosBundleId: 'com.example.chatso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNoIrPYR4Ng24wcDkNVm2m0VNqbjMNmoI',
    appId: '1:447295207162:web:d3286bbf6589a8a9633b43',
    messagingSenderId: '447295207162',
    projectId: 'chatso-2cb01',
    authDomain: 'chatso-2cb01.firebaseapp.com',
    storageBucket: 'chatso-2cb01.firebasestorage.app',
  );
}
